listen_addresses = '*'
port = 5432
max_connections = 100
shared_buffers = '128MB'
wal_level = replica
archive_mode = on
archive_timeout = 60
archive_command = 'test -f /var/lib/pgbackrest/archive/demo/archive.info -o -f /var/lib/pgbackrest/archive/demo/archive.info.copy || exit 0; pgbackrest --stanza=demo archive-push %p'
max_wal_senders = 3
log_destination = 'stderr'
logging_collector = off
hba_file = '/etc/postgresql/pg_hba.conf'
